### ISSUE TITLE
Repository config type default value seems not take effect

### ISSUE THREAD

**Issue by chengzhycn** [LeslieLeung/reaper#18]
This is my configuration yaml originally:
```
repository:
  - name: reaper
    url: github.com/leslieleung/reaper
    cron: "30 * * * *"
    storage:
      - localFile
    useCache: True
  - name: awesome-english-ebooks
    url: xxx
    cron: "30 * * * *"
    storage:
      - localFile
    useCache: True

storage:
  - name: localFile
    type: file
    path: /repo
```

When I started in deamon mode, it output 2 errors:

```
Unknown type
Unknown type
Starting daemon
```

I viewed the source codes, and find that it is because unknown type of repo. So I add `type: "repo"` to each repo's config, It works correctly now.

I think this is a serious problem that could let this program cant work. So I want to make sure that this is actually a bug or I missed something?
